- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1016/j.cell.2021.10.024
  image: https://www.cell.com/cms/attachment/1402ad8d-fb44-45f6-b40a-80b2d19b5890/fx1.jpg
  group: featured

- id: doi:10.1016/j.celrep.2022.111630
  image: https://www.cell.com/cms/attachment/dd685e42-1bfd-4c62-a488-48cc64b0bc04/fx1.jpg

- id: doi:10.1038/s41467-022-33785-w

- id: doi:10.1038/s41586-021-03604-1

- id: doi:10.1126/sciadv.aav3262
  group: featured

- id: doi:10.7554/elife.62522

- id: doi:10.1126/sciadv.abf1444

- id: doi:10.1038/s41467-021-21583-9

- id: doi:10.1534/genetics.120.303597

- id: doi:10.1093/nar/gkz483

- id: doi:10.1038/ncomms12249
  group: featured

- id: doi:10.1038/nature24993

- id: doi:10.1038/ni.3706
  group: featured

- id: doi:10.1073/pnas.1813565116

- id: doi:10.1093/nar/gkr698

- id: doi:10.1093/database/bay017

- id: doi:10.1534/g3.118.200401

- id: doi:10.1038/ncomms10812

- id: doi:10.1038/s41525-019-0077-8
- id: doi:10.1016/j.ymeth.2010.04.005
